
import readline
import sys
import numpy as np
import quantile_normalisation
import noise
import file_handler
import mixtures
import tumor
import copy
import argparse
import config

FLAGS = []
MIXTURES = []
MIXTURES_INPUT = []
TUMORS = []
TUMORS_INPUT = []
CELL_LINES = []
CELL_LINES_INPUT = []
ITERATION = []

parser = argparse.ArgumentParser()
parser.add_argument("-m", "--MIXTURES", help="Mixtures", nargs='*')
parser.add_argument("-t", "--TUMORS", help="Tumors", nargs='*')
parser.add_argument("-c", "--CELL_LINES", help="Cell lines", nargs='*')
parser.add_argument("-r", "--REFERENCE", help="Reference", nargs='*')
parser.add_argument("-i", "--ITERATION", help="Iteration", nargs='*')

args = parser.parse_args()


def read_stdin():

	""" Reads in from keyboard. This is needed to know which part of the input files that are
	supposed to be read by the program.
	"""

	print("")

	if args.MIXTURES != None and len(args.MIXTURES) > 0:

		print("*** MIXTURES ***")

		for i in range(len(args.MIXTURES)):

			no_mixtures = int(input("How many distinct mixtures in " + args.MIXTURES[i] + "? "))
			start = int(input("From which column does the first mixture begin (0 is first column)? "))
			stop = int(input("To which column does the last mixture end? "))
			replicates = int(input("Number of replicates per mixture (type 1 if only one mixture)? "))
			
			MIXTURES_INPUT.append([no_mixtures, start, stop, replicates])

	print("")

	if args.TUMORS != None and len(args.TUMORS) > 0:

		print("*** TUMORS ***")

		for i in range(len(args.TUMORS)):

			no_tumors = int(input("How many tumor cell lines in " + args.TUMORS[i] + "? "))
			start = int(input("From which column does the first tumor cell line begin (0 is first column)? "))
			stop = int(input("To which column does the last tumor cell line end? "))
			replicates = int(input("Number of replicates per tumor cell line (type 1 if only one cell line)? "))
			
			TUMORS_INPUT.append([no_tumors, start, stop, replicates])

	print("")

	if args.CELL_LINES != None and len(args.CELL_LINES) > 0:

		print("*** CELL LINES ***")

		for i in range(len(args.CELL_LINES)):

			no_cell_lines = int(input("How many cell lines in " + args.CELL_LINES[i] + "? "))
			start = int(input("From which column does the first cell line begin (0 is first column)? "))
			stop = int(input("To which column does the last cell line end? "))
			replicates = int(input("Number of replicates per cell line (type 1 if only one cell line)? "))
			
			CELL_LINES_INPUT.append([no_cell_lines, start, stop, replicates])

	print("")


def execute():

	""" This is the function that initiates the whole simulation. There are different possibilities
	for simulation:

	1. Generate a reference file (used for signature matrix in CIBERSORT) using immune cell lines
		and tumor cell lines.
	2. Generate a pure cell lines file (used for LLSR) using immune cell lines and tumor cell lines.
	3. Generate a simulation file with spiked in tumor. This should be generated by using mixture
		files and tumor files.
	"""

	if args.CELL_LINES != None and len(args.CELL_LINES) > 0:
		if args.REFERENCE != None and len(args.REFERENCE) > 0:
			reference()
		else:
			pure_cells()

	if args.MIXTURES != None and len(args.MIXTURES) > 0:
		# mixes()
		test()

def reference():

	""" Generate a reference file (used for signature matrix in CIBERSORT) using immune cell lines
	and tumor cell lines.
	"""

	np_gene_dictionary = {}
	tumor_present = False

	if args.TUMORS != None and len(args.TUMORS) > 0:
		tumor_present = True

	np_gene_dictionary = mixtures.get_relevant_information(np_gene_dictionary, tumor_present, args.CELL_LINES, CELL_LINES_INPUT, args.TUMORS, TUMORS_INPUT)

	separate_values_matrix = mixtures.from_dictionary_to_matrix(np_gene_dictionary)

	cell_lines_matrix = mixtures.get_separated_for_normalization(separate_values_matrix, tumor_present, CELL_LINES_INPUT, TUMORS_INPUT)

	cell_lines_matrix = quantile_normalisation.quantile_normalize_separately(cell_lines_matrix)

	separate_values_matrix = mixtures.gather_separated_normalized_data(separate_values_matrix, cell_lines_matrix)

	separate_values_matrix = quantile_normalisation.algo(separate_values_matrix)

	mixtures.save_separate_matrix(np_gene_dictionary, separate_values_matrix, tumor_present, config.REFERENCE, config.REFERENCE_TUMOR, CELL_LINES_INPUT, TUMORS_INPUT)


def pure_cells():

	""" Generate a pure cell lines file (used for LLSR) using immune cell lines and tumor cell lines.
	"""

	np_gene_dictionary = {}
	tumor_present = False

	if args.TUMORS != None and len(args.TUMORS) > 0:
		tumor_present = True

	np_gene_dictionary = mixtures.get_relevant_information(np_gene_dictionary, tumor_present, args.CELL_LINES, CELL_LINES_INPUT, args.TUMORS, TUMORS_INPUT)

	separate_values_matrix = mixtures.from_dictionary_to_matrix(np_gene_dictionary)

	cell_lines_matrix = mixtures.get_separated_for_normalization(separate_values_matrix, tumor_present, CELL_LINES_INPUT, TUMORS_INPUT)

	cell_lines_matrix = quantile_normalisation.quantile_normalize_separately(cell_lines_matrix)

	all_cell_lines_combined = mixtures.combine_separated_normalized_data(cell_lines_matrix, separate_values_matrix)

	mixtures.save_combined_matrix(np_gene_dictionary, all_cell_lines_combined, tumor_present, config.COMBINED_CELLS, config.COMBINED_CELLS_TUMOR, CELL_LINES_INPUT, TUMORS_INPUT)


def mixes():

	""" Generate a simulation file with spiked in tumor. This should be generated by using mixture
	files and tumor files.
	"""

	np_gene_dictionary = {}
	tumor_present = False

	if args.TUMORS != None and len(args.TUMORS) > 0:
		tumor_present = True

	np_gene_dictionary = mixtures.get_relevant_information(np_gene_dictionary, tumor_present, args.MIXTURES, MIXTURES_INPUT, args.TUMORS, TUMORS_INPUT)
	
	separate_values_matrix = mixtures.from_dictionary_to_matrix(np_gene_dictionary)

	cell_lines_matrix = mixtures.get_separated_for_normalization(separate_values_matrix, tumor_present, MIXTURES_INPUT, TUMORS_INPUT)
	
	""" Calculating the total mRNA in each mixture. Used later in Abbas algorithm.
	"""

	#file_handler.write_probe_values([MIXA, MIXB, MIXC, MIXD], ["MIX A", "MIX B", "MIX C", "MIX D"], "probe_values_mixtures")

	cell_lines_matrix = quantile_normalisation.quantile_normalize_separately(cell_lines_matrix)

	all_cell_lines_combined = mixtures.combine_separated_normalized_data(cell_lines_matrix, separate_values_matrix)

	np_gene_dictionary = mixtures.from_matrix_to_dictionary(all_cell_lines_combined, np_gene_dictionary)
	
	""" The data is then iterated over 0 to 100 percent tumor content with intervals
		of 5 percent. Each iteration is written to file.
	"""
	if tumor_present == False:

		file_handler.write_combined_mixtures(np_gene_dictionary, config.MIXTURE, MIXTURES_INPUT)
	else :

		start_tumor = int(args.ITERATION[0]); stop_tumor = int(args.ITERATION[1]); step_tumor = int(args.ITERATION[2])
		start_noise = int(args.ITERATION[3]); stop_noise = int(args.ITERATION[4]); step_noise = int(args.ITERATION[5])

		for tumor_content in range(start_tumor, stop_tumor, step_tumor):

			for noise_amount in range(start_noise, stop_noise, step_noise):

				fixed_tumor_matrix = []

				for i in range(len(all_cell_lines_combined)):

					temp_list = []

					for k in range(len(all_cell_lines_combined[i]) - 1):
						temp_list.append((all_cell_lines_combined[i][k] * (1-(tumor_content/100))) + all_cell_lines_combined[i][len(all_cell_lines_combined[i])-1] * (tumor_content/100))

					if noise_amount > 0:
						temp_list = noise.add_log_noise_controlled(temp_list, noise_amount)

					fixed_tumor_matrix.append(temp_list)

				np_gene_dictionary = mixtures.from_matrix_to_dictionary(fixed_tumor_matrix, np_gene_dictionary)

				file_handler.write_combined_mixtures_tumor(np_gene_dictionary, config.MIXTURES, tumor_content, noise_amount, MIXTURES_INPUT)

			print("--- Generated simulation file with " + str(tumor_content) + "% tumor content. " + str(int((stop_tumor - tumor_content) / step_tumor)) + " files remaining.")


def test():

	""" Generate a simulation file with spiked in tumor. This should be generated by using mixture
	files and tumor files.
	"""

	np_gene_dictionary = {}
	tumor_present = False

	if args.TUMORS != None and len(args.TUMORS) > 0:
		tumor_present = True

	np_gene_dictionary = mixtures.get_relevant_information(np_gene_dictionary, tumor_present, args.MIXTURES, MIXTURES_INPUT, args.TUMORS, TUMORS_INPUT)
	
	separate_values_matrix = mixtures.from_dictionary_to_matrix(np_gene_dictionary)
	
	""" The data is then iterated over 0 to 100 percent tumor content with intervals
		of 5 percent. Each iteration is written to file.
	"""
	if tumor_present == False:

		file_handler.write_combined_mixtures(np_gene_dictionary, config.MIXTURE, MIXTURES_INPUT)
	else :

		start_tumor = int(args.ITERATION[0]); stop_tumor = int(args.ITERATION[1]); step_tumor = int(args.ITERATION[2])
		start_noise = int(args.ITERATION[3]); stop_noise = int(args.ITERATION[4]); step_noise = int(args.ITERATION[5])

		for tumor_content in range(start_tumor, stop_tumor, step_tumor):

			for noise_amount in range(start_noise, stop_noise, step_noise):

				noise_array = []

				for i in range(len(separate_values_matrix)):

					temp_array = []

					if noise_amount > 0:
						temp_array = noise.add_noise_controlled(separate_values_matrix[i], noise_amount)
					else:
						temp_array = separate_values_matrix[i]

					noise_array.append(temp_array)

				cell_lines_matrix = mixtures.get_separated_for_normalization(noise_array, tumor_present, MIXTURES_INPUT, TUMORS_INPUT)
	
				""" Calculating the total mRNA in each mixture. Used later in Abbas algorithm.
				"""

				cell_lines_matrix = quantile_normalisation.quantile_normalize_separately(cell_lines_matrix)

				all_cell_lines_combined = mixtures.combine_separated_normalized_data(cell_lines_matrix, noise_array)
				
				np_gene_dictionary = mixtures.from_matrix_to_dictionary(all_cell_lines_combined, np_gene_dictionary)

				fixed_tumor_matrix = []

				for i in range(len(all_cell_lines_combined)):

					temp_list = []

					for k in range(len(all_cell_lines_combined[i]) - 1):
						temp_list.append((all_cell_lines_combined[i][k] * (1-(tumor_content/100))) + all_cell_lines_combined[i][len(all_cell_lines_combined[i])-1] * (tumor_content/100))

					fixed_tumor_matrix.append(temp_list)

				np_gene_dictionary = mixtures.from_matrix_to_dictionary(fixed_tumor_matrix, np_gene_dictionary)

				file_handler.write_combined_mixtures_tumor(np_gene_dictionary, config.MIXTURES, tumor_content, noise_amount, MIXTURES_INPUT)

			print("--- Generated simulation file with " + str(tumor_content) + "% tumor content. " + str(int((stop_tumor - tumor_content) / step_tumor)) + " files remaining.")


read_stdin()
execute()